import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function ClaimedMachine({ machine, onRelease, onRenew, releasing, renewing }) {
    const formatDate = (ts) => {
        if (!ts)
            return 'N/A';
        return new Date(ts).toLocaleString();
    };
    const codeServerUrl = machine.publicIp ? `http://${machine.publicIp}:8080` : null;
    const sshCommand = machine.publicIp ? `ssh ubuntu@${machine.publicIp}` : null;
    return (_jsxs("div", { className: "bg-white rounded-lg border border-gray-200 p-6 mb-8", children: [_jsx("h2", { className: "text-xl font-bold text-gray-800 mb-4", children: "Claimed Machine" }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 mb-6", children: [_jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-500", children: "Instance ID" }), _jsx("div", { className: "font-mono text-sm font-medium", children: machine.instanceId })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-500", children: "User ID" }), _jsx("div", { className: "font-mono text-sm font-medium", children: machine.userId || 'N/A' })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-500", children: "Public IP" }), _jsx("div", { className: "font-mono text-sm font-medium", children: machine.publicIp || 'N/A' })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-500", children: "Private IP" }), _jsx("div", { className: "font-mono text-sm font-medium", children: machine.privateIp || 'N/A' })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-500", children: "Lease Expires" }), _jsx("div", { className: "font-mono text-sm font-medium", children: formatDate(machine.leaseExpiry) })] }), _jsxs("div", { children: [_jsx("div", { className: "text-sm text-gray-500", children: "Last Heartbeat" }), _jsx("div", { className: "font-mono text-sm font-medium", children: formatDate(machine.lastHeartbeat) })] })] }), codeServerUrl && (_jsxs("div", { className: "mb-4 p-4 bg-gray-50 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-500 mb-1", children: "Code Server URL" }), _jsx("a", { href: codeServerUrl, target: "_blank", rel: "noopener noreferrer", className: "text-blue-600 hover:underline font-mono", children: codeServerUrl })] })), sshCommand && (_jsxs("div", { className: "mb-6 p-4 bg-gray-50 rounded-lg", children: [_jsx("div", { className: "text-sm text-gray-500 mb-1", children: "SSH Command" }), _jsx("code", { className: "font-mono text-sm", children: sshCommand })] })), _jsxs("div", { className: "flex gap-3", children: [_jsx("button", { onClick: onRenew, disabled: renewing, className: "px-4 py-2 bg-green-600 hover:bg-green-700 disabled:bg-green-300 text-white rounded-lg font-medium transition", children: renewing ? 'Renewing...' : 'Renew Lease (+10 min)' }), _jsx("button", { onClick: onRelease, disabled: releasing, className: "px-4 py-2 bg-red-600 hover:bg-red-700 disabled:bg-red-300 text-white rounded-lg font-medium transition", children: releasing ? 'Releasing...' : 'Release Machine' })] })] }));
}
//# sourceMappingURL=ClaimedMachine.js.map